### Creation of ndarray

* Write python code to create 3d array in different ways with 15 elements.
* Array Creation:
#### a. Create a 4D NumPy array containing the first 12 positive integers as arr1. b. Create a 3D NumPy array1 with 20 random elements containing integers between 0 and 1. 3. Find all attributes of array1 and array2 4. Apply measure and describe the data (attributes and descriptive statistics) to above arrays using NumPy

In [6]:
import numpy as np

a =np.array([[[10,20,30,40,50,60,70,80,90,100,1110,120,130,140,150]]])
a

array([[[  10,   20,   30,   40,   50,   60,   70,   80,   90,  100,
         1110,  120,  130,  140,  150]]])

In [7]:
a.ndim

3

In [8]:
np.array([10,20,30,40,50,60,70,80,90,100,1110,120,130,140,150])

array([  10,   20,   30,   40,   50,   60,   70,   80,   90,  100, 1110,
        120,  130,  140,  150])

In [11]:
a =np.array([10,20,30,40,50,60,70,80,90,100,1110,120,130,140,150],ndmin=3)
a

array([[[  10,   20,   30,   40,   50,   60,   70,   80,   90,  100,
         1110,  120,  130,  140,  150]]])

In [13]:
a =np.array([10,20,30,40,50,60,70,80,90,100,1110,120,130,140,150]).reshape(1,3,5)
a

array([[[  10,   20,   30,   40,   50],
        [  60,   70,   80,   90,  100],
        [1110,  120,  130,  140,  150]]])

In [14]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12],ndmin=4)
arr1

array([[[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]]])

In [15]:
arr1.ndim

4

In [27]:
arr = np.random.rand(1,20)
arr

array([[0.00849035, 0.98092482, 0.90177437, 0.60158706, 0.09141002,
        0.18865   , 0.09293942, 0.56329074, 0.92934213, 0.98024608,
        0.2752982 , 0.20528932, 0.0575723 , 0.23720627, 0.99095291,
        0.86304396, 0.09219517, 0.30144619, 0.83801798, 0.05357906]])

In [28]:
arr.ndim

2

In [29]:
arr.dtype

dtype('float64')

In [30]:
arr.size

20

In [31]:
arr.itemsize

8

In [32]:
arr.nbytes

160

In [33]:
arr1

array([[[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]]])

In [34]:
arr1.size

12

In [35]:
arr1.nbytes

48

In [36]:
arr1.itemsize

4

In [38]:
arr1.dtype

dtype('int32')

In [39]:
arr1.ndim

4

In [43]:
arr1.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [45]:
arr1.mean()

6.5

In [47]:
np.median(arr1)

6.5

In [48]:
arr1.var()

11.916666666666666

In [49]:
arr1.std()

3.452052529534663

In [51]:
range = arr1.max() - arr1.min()
range

11

In [53]:
q1 = np.percentile(arr1,25)
q1

3.75

In [54]:
q3 = np.percentile(arr1,75)
q3

9.25

In [56]:
IQR = q3 - q1
IQR

5.5

In [59]:
lower = q1 - (1.5*IQR)
lower

-4.5

In [60]:
upper = q3 + (1.5*IQR)
upper

17.5

In [61]:
arr1[arr1<lower]

array([], dtype=int32)

In [62]:
arr1[arr1>upper]

array([], dtype=int32)

In [63]:
arr.mean()

0.4626628173394206

In [64]:
np.median(arr)

0.28837219279786336

In [65]:
arr.var()

0.13797756315368953

In [67]:
arr.std()

0.3714533122125707

In [69]:
range = arr.max()-arr.min()
range

0.9824625643498486

In [72]:
q1 = np.percentile(arr,25)
q1

0.09275335593062878

In [74]:
q3 = np.percentile(arr,75)
q3

0.8727265596171064

In [75]:
IQR = q3-q1
IQR

0.7799732036864777

In [76]:
lower = q1 - (1.5*IQR)
lower

-1.0772064495990878

In [77]:
upper = q3 + (1.5*IQR)
upper

2.0426863651468232

In [79]:
arr[arr<lower]

array([], dtype=float64)

In [80]:
arr[arr>upper]

array([], dtype=float64)

### Array Slicing and Indexing:

a. Creating Arrays: - Create a 1-dimensional NumPy array arr1 with the values [0, 11, 26, 73, 42, 51, 6,77, 8,29]. - Create a 2-dimensional NumPy array arr2 with the values [[0, 1, 2], [3, 4, 5], [6, 7, 8]].

b.Basic Indexing: - Print the element at index 3 of arr1. - Print the element at row 2, column 1 of arr2

c. Array Slicing: - Print the first five elements of arr1. - Print the subarray of arr2 consisting of the last two rows and the first two columns. - Print every second element starting from index 1 up to index 7 of arr1.

In [82]:
arr1 = np.array([0, 11, 26, 73, 42, 51, 6,77, 8,29])
arr1

array([ 0, 11, 26, 73, 42, 51,  6, 77,  8, 29])

In [84]:
arr2 = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [85]:
arr1[3]

73

In [86]:
arr2[2,1]

7

In [88]:
arr1[:5]

array([ 0, 11, 26, 73, 42])

In [89]:
arr2[1:,0:2]

array([[3, 4],
       [6, 7]])

In [90]:
arr1[1:8]

array([11, 26, 73, 42, 51,  6, 77])

### Data Type Manipulation

a. Creating Arrays with Specific Data Types: - Create a 1-dimensional NumPy array int_array with the values [1, 2, 3, 4, 5] and the data type int16. - Create a 1-dimensional NumPy array float_array with the values [0.1, 0.2, 0.3, 0.4, 0.5] and the data type float64.

b. Data Type Conversion: - Convert the float_array to an array with data type int32. Print the result. - Convert the int_array to an array with data type float32. Print the result.

In [92]:
int_array = np.array([1,2,3,4,5],dtype ='int16')
int_array

array([1, 2, 3, 4, 5], dtype=int16)

In [93]:
float_array = np.array([0.1,0.2,0.3,0.4,0.5],dtype='float64')
float_array

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [97]:
n = np.array([0.1, 0.2, 0.3, 0.4, 0.5],dtype = "int32")
n

array([0, 0, 0, 0, 0])

In [98]:
n1 = np.array([1, 2, 3, 4, 5],dtype = "float32")
n1

array([1., 2., 3., 4., 5.], dtype=float32)

### Generating Random Numbers:

1. Use numpy.random.randint() to create an array rand_integers containing 10 random integers between 0 and 100 (inclusive).

2. Use numpy.random.uniform() to create an array rand_uniform containing 5 random numbers sampled from a uniform distribution between -1 and 1.

3. Create an array rand_matrix with random integers between 50 and 100 (inclusive).and reshape it to 2-dimensional (4 x 4) matrix

4. Apply descriptive statistics for rand_matrix.

In [100]:
rand_integers = np.random.randint(0,101,10)
rand_integers

array([96, 88,  5, 40, 27, 22, 25, 96, 17, 10])

In [101]:
rand_uniform = np.random.uniform(-1,1,5)
rand_uniform

array([-0.1436822 ,  0.16479601,  0.83710109, -0.01094622, -0.21900636])

In [102]:
rand_matrix = np.random.randint(50,101,16).reshape(4,4)
rand_matrix

array([[62, 88, 64, 52],
       [64, 66, 75, 64],
       [80, 68, 61, 52],
       [77, 86, 88, 84]])

In [103]:
rand_matrix.mean()

70.6875

In [105]:
np.median(rand_matrix)

67.0

In [106]:
range = rand_matrix.max()-rand_matrix.min()
range

36

In [107]:
q1 = np.percentile(rand_matrix,25)
q1

63.5

In [108]:
q3 = np.percentile(rand_matrix,75)
q3

81.0

In [109]:
IQR = q3-q1
IQR

17.5

In [110]:
rand_matrix.var()

136.71484375

In [111]:
rand_matrix.std()

11.692512294199224

In [112]:
lower = q1 - (1.5 * IQR)
lower

37.25

In [113]:
upper = q3 + (1.5 * IQR)
upper

107.25

In [114]:
rand_matrix[rand_matrix < lower]

array([], dtype=int32)

In [115]:
rand_matrix[rand_matrix > upper]

array([], dtype=int32)

### Analyze the Data:

Salaries = [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]

Q) Describe the data using numpy array. Measure the following:

1. How many employees are getting more less than 50000?

2. Is it following Normal Distribution?

3. What is the median salary?

4. What is the range of salaries for this company?

5. Find the salaries between average salary and 75% of salaries?

6. How many employees are getting less than 25 % of salaries ?

In [126]:
Salaries = np.array([87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638])

In [127]:
Salaries[Salaries < 50000]

array([31250, 39828, 41671, 34225, 32199])

In [128]:
np.median(Salaries)

61699.5

In [129]:
range = Salaries.max()-Salaries.min()
range

3082388

In [136]:
avg = Salaries.mean()
avg

166169.16666666666

In [137]:
q1 = np.percentile(Salaries,25)
q1

52963.25

In [138]:
q3 = np.percentile(Salaries,75)
q3

84496.5

In [140]:
Salaries[(Salaries > avg) & (Salaries <= q3)]

array([], dtype=int32)

In [142]:
Salaries[Salaries < q1]

array([52453, 31250, 39828, 41671, 51428, 50477, 34225, 32199])