### Task


1. clean the data(outlier,missing values,type conversion)
2. What is the mean value of sepal length
3. sort the sepal width in ascending order.
4. apply all statistical measures on sepal width and length
5. after cleaning the data ,save the file as 'cleaned_iris.txt' and load to jupyter again to display the values

In [2]:
import numpy as np

In [8]:
a = np.genfromtxt(r"C:\Users\m\Downloads\Iris_clean_-_Copy.csv",dtype = 'float32', delimiter= ',')
a

array([[      nan,       nan,       nan,       nan],
       [5.100e+00, 3.500e+00, 1.400e+00, 2.000e-01],
       [4.900e+00, 3.000e+00, 1.400e+00, 2.000e-01],
       [4.700e+00, 3.200e+00, 1.300e+00, 2.000e-01],
       [4.600e+00, 3.100e+00, 1.500e+00, 1.020e+01],
       [5.000e+01, 3.600e+00, 1.400e+00, 2.000e-01],
       [5.400e+00,       nan, 1.700e+00, 4.000e-01],
       [4.600e+00, 3.400e+00, 1.400e+00, 3.000e-01],
       [5.000e+00, 3.400e+00, 1.500e+00, 2.000e-01],
       [4.400e+00, 2.900e+00, 1.400e+00, 2.000e-01],
       [4.900e+00, 3.100e+00,       nan, 1.000e-01],
       [5.400e+00, 3.700e+00, 1.500e+00, 2.000e-01],
       [4.800e+00, 3.400e+00, 1.600e+00, 2.000e-01],
       [4.800e+00, 1.300e+02, 1.400e+00, 1.010e+01],
       [4.300e+00, 3.000e+00, 1.100e+00, 1.000e-01],
       [5.800e+00, 4.000e+00, 1.200e+00, 2.000e-01],
       [5.700e+00, 4.400e+00, 1.500e+00, 4.000e-01],
       [5.040e+01,       nan, 1.300e+00, 4.000e-01],
       [5.100e+00, 3.500e+00, 1.400e+00, 3.000

In [9]:
sepal_length = a[1:,0]
sepal_length

array([  5.1,   4.9,   4.7,   4.6,  50. ,   5.4,   4.6,   5. ,   4.4,
         4.9,   5.4,   4.8,   4.8,   4.3,   5.8,   5.7,  50.4,   5.1,
         5.7,   5.1,   5.4,   5.1,   4.6,   5.1,   4.8,   5. ,   5. ,
         5.2,   5.2,   4.7,   4.8,   5.4,   5.2,   5.5,   4.9,   5. ,
         5.5,   4.9,   4.4,   5.1,   5. ,   4.5,   4.4,   5. ,   5.1,
         4.8,   5.1,   4.6,   5.3,   5. ,   7. ,   6.4,   6.9,   5.5,
         6.5,   5.7, 116.3,   4.9,   6.6,   5.2,   5. ,   5.9,   6. ,
         6.1,   5.6,   6.7,   5.6,   5.8,   6.2,   5.6,   5.9,   6.1,
         6.3,   6.1,   6.4,   6.6,   6.8,   6.7,   6. ,   5.7,   5.5,
         5.5,   5.8,   6. ,   5.4,   6. ,   6.7,   6.3,   5.6,   5.5,
         5.5,   6.1,   5.8,   5. ,   5.6,   5.7,   5.7,   6.2,   5.1,
         5.7,   6.3,   5.8,   7.1,   6.3,   6.5,   7.6,   4.9,   7.3,
         6.7,   7.2,   6.5,   6.4,   6.8,   5.7,   5.8,   6.4,   6.5,
         7.7,   7.7,   6. ,   6.9,   5.6,   7.7,   6.3,   6.7,   7.2,
         6.2,   6.1,

In [10]:
median = np.nanmedian(sepal_length)
median

5.8

In [11]:
sepal_length[sepal_length>6]

array([ 50. ,  50.4,   7. ,   6.4,   6.9,   6.5, 116.3,   6.6,   6.1,
         6.7,   6.2,   6.1,   6.3,   6.1,   6.4,   6.6,   6.8,   6.7,
         6.7,   6.3,   6.1,   6.2,   6.3,   7.1,   6.3,   6.5,   7.6,
         7.3,   6.7,   7.2,   6.5,   6.4,   6.8,   6.4,   6.5,   7.7,
         7.7,   6.9,   7.7,   6.3,   6.7,   7.2,   6.2,   6.1,   6.4,
        70.2,   6.4,   6.3,   6.1,   7.7,   6.3,   6.4,   6.9,   6.7,
         6.9,   6.8,   6.7,   6.7,   6.3,   6.5,   6.2,   7.7,   7.2,
         7.3,   6.7,   7.7,   6.3,   7.2,   6.5,   6.4], dtype=float32)

In [12]:
sepal_length = np.where(sepal_length>6,median,sepal_length)
sepal_length

array([5.1, 4.9, 4.7, 4.6, 5.8, 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.8, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 5.8, 5.8,
       5.8, 5.5, 5.8, 5.7, 5.8, 4.9, 5.8, 5.2, 5. , 5.9, 6. , 5.8, 5.6,
       5.8, 5.6, 5.8, 5.8, 5.6, 5.9, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 5.8, 5.8, 5.6, 5.5, 5.5,
       5.8, 5.8, 5. , 5.6, 5.7, 5.7, 5.8, 5.1, 5.7, 5.8, 5.8, 5.8, 5.8,
       5.8, 5.8, 4.9, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.7, 5.8, 5.8, 5.8,
       5.8, 5.8, 6. , 5.8, 5.6, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8,
       nan, nan, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 6. , 5.8, 5.8, 5.8, 5.8,
       5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.9, 5.6, 5.8, nan, nan, 5.8, 4.9,
       5.8, 5.8, 5.9, 5.6, 5.8, 5.8, 5.8, 5.8, 5.8], dtype=float32)

In [13]:
sepal_length = np.where(np.isnan(sepal_length),median,sepal_length)
sepal_length

array([5.1, 4.9, 4.7, 4.6, 5.8, 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.8, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 5.8, 5.8,
       5.8, 5.5, 5.8, 5.7, 5.8, 4.9, 5.8, 5.2, 5. , 5.9, 6. , 5.8, 5.6,
       5.8, 5.6, 5.8, 5.8, 5.6, 5.9, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 5.8, 5.8, 5.6, 5.5, 5.5,
       5.8, 5.8, 5. , 5.6, 5.7, 5.7, 5.8, 5.1, 5.7, 5.8, 5.8, 5.8, 5.8,
       5.8, 5.8, 4.9, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.7, 5.8, 5.8, 5.8,
       5.8, 5.8, 6. , 5.8, 5.6, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8,
       5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 6. , 5.8, 5.8, 5.8, 5.8,
       5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.9, 5.6, 5.8, 5.8, 5.8, 5.8, 4.9,
       5.8, 5.8, 5.9, 5.6, 5.8, 5.8, 5.8, 5.8, 5.8], dtype=float32)

In [15]:
sepal_width = a[1:,1]
sepal_width

array([  3.5,   3. ,   3.2,   3.1,   3.6,   nan,   3.4,   3.4,   2.9,
         3.1,   3.7,   3.4, 130. ,   3. ,   4. ,   4.4,   nan,   3.5,
         3.8,   3.8,   3.4,   3.7,   3.6,   3.3,   3.4,   3. ,  34. ,
         3.5,   3.4,   3.2,   3.1,   3.4,   4.1,   4.2,   3.1,   3.2,
         3.5,   3.1,   3. ,   3.4,   3.5,   2.3,   3.2,   3.5,   3.8,
         3. ,   3.8,   3.2,   3.7,   3.3,   3.2,   3.2,   nan,   2.3,
         2.8,   2.8,   3.3,   2.4,   2.9,   2.7,   2. ,   3. ,   2.2,
         2.9,   2.9,   3.1,   3. ,   2.7,   2.2,   2.5,   3.2,   2.8,
         2.5,   nan,   2.9,   3. ,   2.8,   3. ,   2.9,   2.6,   2.4,
         2.4,   2.7,   2.7,   3. ,   3.4,   3.1,   2.3,   3. ,   2.5,
         2.6,   3. , 112.6,   2.3,   2.7,   3. ,   2.9,   2.9,   2.5,
         2.8,   3.3,   2.7,   3. ,   2.9,   3. ,   3. ,   2.5,   2.9,
         2.5,   3.6,   3.2,   2.7,   3. ,   2.5,   2.8,   3.2,   3. ,
         3.8,   2.6,   2.2,   3.2,   2.8,   2.8,   2.7,   3.3,   3.2,
         2.8,   3. ,

In [16]:
median = np.nanmedian(sepal_width)
median

3.0

In [17]:
sepal_width[sepal_width>3.4]

array([  3.5,   3.6,   3.7, 130. ,   4. ,   4.4,   3.5,   3.8,   3.8,
         3.7,   3.6,  34. ,   3.5,   4.1,   4.2,   3.5,   3.5,   3.5,
         3.8,   3.8,   3.7, 112.6,   3.6,   3.8,   3.8,   3.6],
      dtype=float32)

In [18]:
sepal_width = np.where(sepal_width>3.4,median,sepal_width)
sepal_width

array([3. , 3. , 3.2, 3.1, 3. , nan, 3.4, 3.4, 2.9, 3.1, 3. , 3.4, 3. ,
       3. , 3. , 3. , nan, 3. , 3. , 3. , 3.4, 3. , 3. , 3.3, 3.4, 3. ,
       3. , 3. , 3.4, 3.2, 3.1, 3.4, 3. , 3. , 3.1, 3.2, 3. , 3.1, 3. ,
       3.4, 3. , 2.3, 3.2, 3. , 3. , 3. , 3. , 3.2, 3. , 3.3, 3.2, 3.2,
       nan, 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 2. , 3. , 2.2, 2.9, 2.9,
       3.1, 3. , 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, nan, 2.9, 3. , 2.8, 3. ,
       2.9, 2.6, 2.4, 2.4, 2.7, 2.7, 3. , 3.4, 3.1, 2.3, 3. , 2.5, 2.6,
       3. , 3. , 2.3, 2.7, 3. , 2.9, 2.9, 2.5, 2.8, 3.3, 2.7, 3. , 2.9,
       3. , 3. , 2.5, 2.9, 2.5, 3. , 3.2, 2.7, 3. , 2.5, 2.8, 3.2, 3. ,
       3. , 2.6, 2.2, 3.2, 2.8, 2.8, 2.7, 3.3, 3.2, 2.8, 3. , 2.8, 3. ,
       2.8, 3. , 2.8, 2.8, 2.6, 3. , 3.4, nan, 3. , 3.1, 3.1, 3.1, 2.7,
       3.2, 3.3, nan, 2.5, 3. , 3.4, 3. , 2.8, 2.8, 2.7, 3.3, 3.2, 2.5,
       2.9, 2.5, 3. , 2.8, 2.8, 2.7, 3. , 3.2, 2.7], dtype=float32)

In [19]:
sepal_width = np.where(np.isnan(sepal_width),median,sepal_width)
sepal_width

array([3. , 3. , 3.2, 3.1, 3. , 3. , 3.4, 3.4, 2.9, 3.1, 3. , 3.4, 3. ,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3.4, 3. , 3. , 3.3, 3.4, 3. ,
       3. , 3. , 3.4, 3.2, 3.1, 3.4, 3. , 3. , 3.1, 3.2, 3. , 3.1, 3. ,
       3.4, 3. , 2.3, 3.2, 3. , 3. , 3. , 3. , 3.2, 3. , 3.3, 3.2, 3.2,
       3. , 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 2. , 3. , 2.2, 2.9, 2.9,
       3.1, 3. , 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, 3. , 2.9, 3. , 2.8, 3. ,
       2.9, 2.6, 2.4, 2.4, 2.7, 2.7, 3. , 3.4, 3.1, 2.3, 3. , 2.5, 2.6,
       3. , 3. , 2.3, 2.7, 3. , 2.9, 2.9, 2.5, 2.8, 3.3, 2.7, 3. , 2.9,
       3. , 3. , 2.5, 2.9, 2.5, 3. , 3.2, 2.7, 3. , 2.5, 2.8, 3.2, 3. ,
       3. , 2.6, 2.2, 3.2, 2.8, 2.8, 2.7, 3.3, 3.2, 2.8, 3. , 2.8, 3. ,
       2.8, 3. , 2.8, 2.8, 2.6, 3. , 3.4, 3. , 3. , 3.1, 3.1, 3.1, 2.7,
       3.2, 3.3, 3. , 2.5, 3. , 3.4, 3. , 2.8, 2.8, 2.7, 3.3, 3.2, 2.5,
       2.9, 2.5, 3. , 2.8, 2.8, 2.7, 3. , 3.2, 2.7], dtype=float32)

In [21]:
petal_length = a[1:,2]
petal_length

array([ 1.4,  1.4,  1.3,  1.5,  1.4,  1.7,  1.4,  1.5,  1.4,  nan,  1.5,
        1.6,  1.4,  1.1,  1.2,  1.5,  1.3,  1.4,  1.7,  1.5,  1.7,  1.5,
        1. ,  1.7,  1.9,  1.6,  1.6,  1.5,  1.4,  1.6,  1.6,  1.5,  1.5,
        1.4,  1.5,  1.2,  1.3,  1.5,  1.3,  1.5,  1.3, 13. ,  1.3,  1.6,
        1.9,  1.4,  1.6,  1.4,  1.5,  1.4,  4.7,  4.5,  4.9,  4. ,  4.6,
        4.5,  4.7,  3.3,  4.6,  3.9,  3.5,  4.2,  4. ,  4.7,  3.6,  4.4,
        4.5,  4.1,  4.5,  3.9,  4.8,  4. ,  4.9,  4.7,  4.3,  4.4,  4.8,
        5. ,  4.5,  3.5, 13.8,  3.7,  3.9,  5.1,  4.5,  4.5,  4.7,  4.4,
        4.1,  4. ,  4.4,  nan,  4. ,  3.3,  4.2,  4.2,  4.2,  4.3,  3. ,
        4.1,  6. ,  5.1,  5.9,  5.6,  5.8,  6.6,  4.5,  6.3,  5.8,  6.1,
        5.1,  5.3,  nan,  5. ,  5.1,  5.3,  5.5,  6.7,  6.9,  5. ,  5.7,
        4.9,  6.7,  4.9,  5.7,  6. ,  4.8,  4.9,  5.6,  5.8,  6.1,  nan,
        5.6,  5.1,  5.6,  6.1,  5.6,  5.5,  4.8,  5.4,  nan,  5.1,  5.1,
        5.9,  5.7,  nan,  5. ,  5.2,  5.4,  5.1,  4

In [22]:
median = np.nanmean(petal_length)
median

4.022641

In [23]:
petal_length[petal_length>5]

array([13. , 13.8,  5.1,  6. ,  5.1,  5.9,  5.6,  5.8,  6.6,  6.3,  5.8,
        6.1,  5.1,  5.3,  5.1,  5.3,  5.5,  6.7,  6.9,  5.7,  6.7,  5.7,
        6. ,  5.6,  5.8,  6.1,  5.6,  5.1,  5.6,  6.1,  5.6,  5.5,  5.4,
        5.1,  5.1,  5.9,  5.7,  5.2,  5.4,  5.1,  6.7,  5.7,  6. ,  6.3,
        5.8,  5.1,  6.7,  6.1,  5.1,  5.3], dtype=float32)

In [24]:
petal_length = np.where(petal_length>5,median,petal_length)
petal_length

array([1.4     , 1.4     , 1.3     , 1.5     , 1.4     , 1.7     ,
       1.4     , 1.5     , 1.4     ,      nan, 1.5     , 1.6     ,
       1.4     , 1.1     , 1.2     , 1.5     , 1.3     , 1.4     ,
       1.7     , 1.5     , 1.7     , 1.5     , 1.      , 1.7     ,
       1.9     , 1.6     , 1.6     , 1.5     , 1.4     , 1.6     ,
       1.6     , 1.5     , 1.5     , 1.4     , 1.5     , 1.2     ,
       1.3     , 1.5     , 1.3     , 1.5     , 1.3     , 4.022641,
       1.3     , 1.6     , 1.9     , 1.4     , 1.6     , 1.4     ,
       1.5     , 1.4     , 4.7     , 4.5     , 4.9     , 4.      ,
       4.6     , 4.5     , 4.7     , 3.3     , 4.6     , 3.9     ,
       3.5     , 4.2     , 4.      , 4.7     , 3.6     , 4.4     ,
       4.5     , 4.1     , 4.5     , 3.9     , 4.8     , 4.      ,
       4.9     , 4.7     , 4.3     , 4.4     , 4.8     , 5.      ,
       4.5     , 3.5     , 4.022641, 3.7     , 3.9     , 4.022641,
       4.5     , 4.5     , 4.7     , 4.4     , 4.1     , 4.   

In [25]:
petal_length = np.where(np.isnan(petal_length),median,petal_length)
petal_length

array([1.4     , 1.4     , 1.3     , 1.5     , 1.4     , 1.7     ,
       1.4     , 1.5     , 1.4     , 4.022641, 1.5     , 1.6     ,
       1.4     , 1.1     , 1.2     , 1.5     , 1.3     , 1.4     ,
       1.7     , 1.5     , 1.7     , 1.5     , 1.      , 1.7     ,
       1.9     , 1.6     , 1.6     , 1.5     , 1.4     , 1.6     ,
       1.6     , 1.5     , 1.5     , 1.4     , 1.5     , 1.2     ,
       1.3     , 1.5     , 1.3     , 1.5     , 1.3     , 4.022641,
       1.3     , 1.6     , 1.9     , 1.4     , 1.6     , 1.4     ,
       1.5     , 1.4     , 4.7     , 4.5     , 4.9     , 4.      ,
       4.6     , 4.5     , 4.7     , 3.3     , 4.6     , 3.9     ,
       3.5     , 4.2     , 4.      , 4.7     , 3.6     , 4.4     ,
       4.5     , 4.1     , 4.5     , 3.9     , 4.8     , 4.      ,
       4.9     , 4.7     , 4.3     , 4.4     , 4.8     , 5.      ,
       4.5     , 3.5     , 4.022641, 3.7     , 3.9     , 4.022641,
       4.5     , 4.5     , 4.7     , 4.4     , 4.1     , 4.   

In [26]:
petal_width = a[1:,3]
petal_width

array([2.000e-01, 2.000e-01, 2.000e-01, 1.020e+01, 2.000e-01, 4.000e-01,
       3.000e-01, 2.000e-01, 2.000e-01, 1.000e-01, 2.000e-01, 2.000e-01,
       1.010e+01, 1.000e-01, 2.000e-01, 4.000e-01, 4.000e-01, 3.000e-01,
       3.000e-01, 3.000e-01, 2.000e-01, 4.000e-01, 2.000e-01, 5.000e-01,
       2.000e-01, 2.000e-01, 4.000e-01, 2.000e-01, 1.102e+02, 2.000e-01,
       2.000e-01, 4.000e-01, 1.000e-01, 2.000e-01, 1.000e-01, 2.000e-01,
       2.000e-01, 1.000e-01, 2.000e-01, 2.000e-01, 3.000e-01, 3.000e-01,
       2.000e-01, 6.000e-01, 4.000e-01, 3.000e-01, 2.000e-01, 2.000e-01,
       2.000e-01, 2.000e-01, 1.400e+00, 1.500e+00, 1.500e+00, 1.300e+00,
       1.500e+00, 1.300e+00, 1.600e+00, 1.600e+01, 1.300e+00, 1.400e+00,
       1.000e+00, 1.500e+00, 1.000e+00, 1.400e+00, 1.300e+00, 1.400e+00,
       1.500e+00, 1.000e+00, 1.500e+00, 1.100e+00, 1.800e+00, 1.300e+00,
       1.500e+00, 1.200e+00, 1.300e+00, 1.400e+00, 1.400e+00, 1.700e+00,
       1.500e+00, 1.000e+00, 1.100e+00, 1.000e+00, 

In [27]:
median = np.nanmedian(petal_width)
median

1.5

In [28]:
petal_width[petal_width>2]

array([ 10.2,  10.1, 110.2,  16. , 111.1,   2.5,   2.1,   2.2,   2.1,
         2.5,   2.1,   2.4,   2.3,   2.2,   2.3,   2.3,   2.1,   2.1,
         2.2,   2.3,   2.4,   2.1,   2.4,   2.3,   2.3,   2.5,   2.3,
         2.3,   2.1,   2.5], dtype=float32)

In [29]:
petal_width = np.where(petal_width>2,median,petal_width)
petal_width

array([0.2, 0.2, 0.2, 1.5, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 1.5,
       0.1, 0.2, 0.4, 0.4, 0.3, 0.3, 0.3, 0.2, 0.4, 0.2, 0.5, 0.2, 0.2,
       0.4, 0.2, 1.5, 0.2, 0.2, 0.4, 0.1, 0.2, 0.1, 0.2, 0.2, 0.1, 0.2,
       0.2, 0.3, 0.3, 0.2, 0.6, 0.4, 0.3, 0.2, 0.2, 0.2, 0.2, 1.4, 1.5,
       1.5, 1.3, 1.5, 1.3, 1.6, 1.5, 1.3, 1.4, 1. , 1.5, 1. , 1.4, 1.3,
       1.4, 1.5, 1. , 1.5, 1.1, 1.8, 1.3, 1.5, 1.2, 1.3, 1.4, 1.4, 1.7,
       1.5, 1. , 1.1, 1. , 1.2, 1.6, 1.5, 1.6, 1.5, 1.3, 1.3, 1.3, 1.2,
       1.4, 1.2, 1. , 1.3, 1.2, 1.3, 1.3, 1.5, 1.3, 1.5, 1.9, 1.5, 1.8,
       1.5, 1.5, 1.7, 1.8, 1.8, 1.5, 2. , 1.9, 1.5, 2. , 1.5, 1.5, 1.8,
       1.5, 1.5, 1.5, 1.5, 2. , 2. , 1.8, 1.5, 1.8, 1.8, 1.8, 1.5, 1.6,
       1.9, 2. , 1.5, 1.5, 1.4, 1.5, 1.5, 1.8, 1.8, 1.5, 1.5, 1.5, 1.9,
       1.5, 1.5, 1.5, 1.9, 2. , 1.5, 1.8, 2. , 2. , 1.8, 1.5, 1.8, 1.7,
       1.8, 1.8, 1.8, 2. , 2. , 1.8, 1.5, 2. , 1.9], dtype=float32)

In [30]:
petal_width = np.where(np.isnan(petal_width),median,petal_width)
petal_width

array([0.2, 0.2, 0.2, 1.5, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 1.5,
       0.1, 0.2, 0.4, 0.4, 0.3, 0.3, 0.3, 0.2, 0.4, 0.2, 0.5, 0.2, 0.2,
       0.4, 0.2, 1.5, 0.2, 0.2, 0.4, 0.1, 0.2, 0.1, 0.2, 0.2, 0.1, 0.2,
       0.2, 0.3, 0.3, 0.2, 0.6, 0.4, 0.3, 0.2, 0.2, 0.2, 0.2, 1.4, 1.5,
       1.5, 1.3, 1.5, 1.3, 1.6, 1.5, 1.3, 1.4, 1. , 1.5, 1. , 1.4, 1.3,
       1.4, 1.5, 1. , 1.5, 1.1, 1.8, 1.3, 1.5, 1.2, 1.3, 1.4, 1.4, 1.7,
       1.5, 1. , 1.1, 1. , 1.2, 1.6, 1.5, 1.6, 1.5, 1.3, 1.3, 1.3, 1.2,
       1.4, 1.2, 1. , 1.3, 1.2, 1.3, 1.3, 1.5, 1.3, 1.5, 1.9, 1.5, 1.8,
       1.5, 1.5, 1.7, 1.8, 1.8, 1.5, 2. , 1.9, 1.5, 2. , 1.5, 1.5, 1.8,
       1.5, 1.5, 1.5, 1.5, 2. , 2. , 1.8, 1.5, 1.8, 1.8, 1.8, 1.5, 1.6,
       1.9, 2. , 1.5, 1.5, 1.4, 1.5, 1.5, 1.8, 1.8, 1.5, 1.5, 1.5, 1.9,
       1.5, 1.5, 1.5, 1.9, 2. , 1.5, 1.8, 2. , 2. , 1.8, 1.5, 1.8, 1.7,
       1.8, 1.8, 1.8, 2. , 2. , 1.8, 1.5, 2. , 1.9], dtype=float32)

2.   What is the mean value of sepal length

In [32]:
sepal_length.mean()

5.5175753

3. sort the sepal width in ascending order.

In [33]:
np.sort(sepal_width)

array([2. , 2.2, 2.2, 2.2, 2.3, 2.3, 2.3, 2.3, 2.4, 2.4, 2.4, 2.5, 2.5,
       2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.6, 2.6, 2.6, 2.6, 2.7,
       2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.8, 2.8,
       2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8,
       2.8, 2.8, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. ,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. ,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. ,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. ,
       3. , 3. , 3. , 3. , 3. , 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1,
       3.1, 3.1, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2,
       3.2, 3.2, 3.2, 3.2, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3, 3.4, 3.4,
       3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4], dtype=float32)

4. apply all statistical measures on sepal width and length



### Statistical Measures on SepalWidth

In [34]:
sepal_width

array([3. , 3. , 3.2, 3.1, 3. , 3. , 3.4, 3.4, 2.9, 3.1, 3. , 3.4, 3. ,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3.4, 3. , 3. , 3.3, 3.4, 3. ,
       3. , 3. , 3.4, 3.2, 3.1, 3.4, 3. , 3. , 3.1, 3.2, 3. , 3.1, 3. ,
       3.4, 3. , 2.3, 3.2, 3. , 3. , 3. , 3. , 3.2, 3. , 3.3, 3.2, 3.2,
       3. , 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 2. , 3. , 2.2, 2.9, 2.9,
       3.1, 3. , 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, 3. , 2.9, 3. , 2.8, 3. ,
       2.9, 2.6, 2.4, 2.4, 2.7, 2.7, 3. , 3.4, 3.1, 2.3, 3. , 2.5, 2.6,
       3. , 3. , 2.3, 2.7, 3. , 2.9, 2.9, 2.5, 2.8, 3.3, 2.7, 3. , 2.9,
       3. , 3. , 2.5, 2.9, 2.5, 3. , 3.2, 2.7, 3. , 2.5, 2.8, 3.2, 3. ,
       3. , 2.6, 2.2, 3.2, 2.8, 2.8, 2.7, 3.3, 3.2, 2.8, 3. , 2.8, 3. ,
       2.8, 3. , 2.8, 2.8, 2.6, 3. , 3.4, 3. , 3. , 3.1, 3.1, 3.1, 2.7,
       3.2, 3.3, 3. , 2.5, 3. , 3.4, 3. , 2.8, 2.8, 2.7, 3.3, 3.2, 2.5,
       2.9, 2.5, 3. , 2.8, 2.8, 2.7, 3. , 3.2, 2.7], dtype=float32)

In [35]:
sepal_width.mean()

2.9260604

In [36]:
np.median(sepal_width)

3.0

In [37]:
range = np.max(sepal_width)-np.min(sepal_width)
range

1.4000001

In [38]:
q1 = np.quantile(sepal_width,0.25)
q1

2.799999952316284

In [39]:
q3 = np.quantile(sepal_width,0.75)
q3

3.0999999046325684

In [40]:
IQR = q3-q1
IQR

0.2999999523162842

In [41]:
lower = q1 - (1.5*IQR)
lower

2.350000023841858

In [42]:
upper = q3 + (1.5*IQR)
upper

3.5499998331069946

In [43]:
sepal_width[sepal_width<lower]

array([2.3, 2.3, 2. , 2.2, 2.2, 2.3, 2.3, 2.2], dtype=float32)

In [44]:
sepal_width[sepal_width<upper]

array([3. , 3. , 3.2, 3.1, 3. , 3. , 3.4, 3.4, 2.9, 3.1, 3. , 3.4, 3. ,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3.4, 3. , 3. , 3.3, 3.4, 3. ,
       3. , 3. , 3.4, 3.2, 3.1, 3.4, 3. , 3. , 3.1, 3.2, 3. , 3.1, 3. ,
       3.4, 3. , 2.3, 3.2, 3. , 3. , 3. , 3. , 3.2, 3. , 3.3, 3.2, 3.2,
       3. , 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 2. , 3. , 2.2, 2.9, 2.9,
       3.1, 3. , 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, 3. , 2.9, 3. , 2.8, 3. ,
       2.9, 2.6, 2.4, 2.4, 2.7, 2.7, 3. , 3.4, 3.1, 2.3, 3. , 2.5, 2.6,
       3. , 3. , 2.3, 2.7, 3. , 2.9, 2.9, 2.5, 2.8, 3.3, 2.7, 3. , 2.9,
       3. , 3. , 2.5, 2.9, 2.5, 3. , 3.2, 2.7, 3. , 2.5, 2.8, 3.2, 3. ,
       3. , 2.6, 2.2, 3.2, 2.8, 2.8, 2.7, 3.3, 3.2, 2.8, 3. , 2.8, 3. ,
       2.8, 3. , 2.8, 2.8, 2.6, 3. , 3.4, 3. , 3. , 3.1, 3.1, 3.1, 2.7,
       3.2, 3.3, 3. , 2.5, 3. , 3.4, 3. , 2.8, 2.8, 2.7, 3.3, 3.2, 2.5,
       2.9, 2.5, 3. , 2.8, 2.8, 2.7, 3. , 3.2, 2.7], dtype=float32)

In [45]:
np.var(sepal_width)

0.079745084

In [46]:
np.std(sepal_width)

0.28239173

### Statistical Measures on SepalLength

In [47]:
sepal_length

array([5.1, 4.9, 4.7, 4.6, 5.8, 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.8, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 5.8, 5.8,
       5.8, 5.5, 5.8, 5.7, 5.8, 4.9, 5.8, 5.2, 5. , 5.9, 6. , 5.8, 5.6,
       5.8, 5.6, 5.8, 5.8, 5.6, 5.9, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 5.8, 5.8, 5.6, 5.5, 5.5,
       5.8, 5.8, 5. , 5.6, 5.7, 5.7, 5.8, 5.1, 5.7, 5.8, 5.8, 5.8, 5.8,
       5.8, 5.8, 4.9, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.7, 5.8, 5.8, 5.8,
       5.8, 5.8, 6. , 5.8, 5.6, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8,
       5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 6. , 5.8, 5.8, 5.8, 5.8,
       5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.9, 5.6, 5.8, 5.8, 5.8, 5.8, 4.9,
       5.8, 5.8, 5.9, 5.6, 5.8, 5.8, 5.8, 5.8, 5.8], dtype=float32)

In [48]:
sepal_length.mean()

5.5175753

In [49]:
np.median(sepal_length)

5.8

In [50]:
range = np.max(sepal_length) - np.min(sepal_length)
range

1.6999998

In [51]:
q1 = np.quantile(sepal_length,0.25)
q1

5.199999809265137

In [52]:
q3 = np.quantile(sepal_length,0.75)
q3

5.800000190734863

In [53]:
IQR = q3-q1
IQR

0.6000003814697266

In [54]:
lower = q1 - (1.5 * IQR)
lower

4.299999237060547

In [55]:
upper = q3 - (1.5 * IQR)
upper

4.899999618530273

In [56]:
sepal_length[sepal_length<lower]

array([], dtype=float32)

In [57]:
sepal_length[sepal_length<upper]

array([4.7, 4.6, 4.6, 4.4, 4.8, 4.8, 4.3, 4.6, 4.8, 4.7, 4.8, 4.4, 4.5,
       4.4, 4.8, 4.6], dtype=float32)

In [58]:
np.var(sepal_length)

0.17866085

In [59]:
np.std(sepal_length)

0.4226829

5.  after cleaning the data ,save the file as 'cleaned_iris.txt' and load to jupyter again to display the values

In [60]:
np.savez("cleaned.npz",sepal_length,sepal_width,petal_length,petal_width)

In [61]:
a = np.load("cleaned.npz")
a.files

['arr_0', 'arr_1', 'arr_2', 'arr_3']

In [62]:
a['arr_0'] #sepal_length

array([5.1, 4.9, 4.7, 4.6, 5.8, 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.8, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 5.8, 5.8,
       5.8, 5.5, 5.8, 5.7, 5.8, 4.9, 5.8, 5.2, 5. , 5.9, 6. , 5.8, 5.6,
       5.8, 5.6, 5.8, 5.8, 5.6, 5.9, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 5.8, 5.8, 5.6, 5.5, 5.5,
       5.8, 5.8, 5. , 5.6, 5.7, 5.7, 5.8, 5.1, 5.7, 5.8, 5.8, 5.8, 5.8,
       5.8, 5.8, 4.9, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.7, 5.8, 5.8, 5.8,
       5.8, 5.8, 6. , 5.8, 5.6, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8,
       5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 6. , 5.8, 5.8, 5.8, 5.8,
       5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.9, 5.6, 5.8, 5.8, 5.8, 5.8, 4.9,
       5.8, 5.8, 5.9, 5.6, 5.8, 5.8, 5.8, 5.8, 5.8], dtype=float32)

In [63]:
a['arr_1'] #sepal_width

array([3. , 3. , 3.2, 3.1, 3. , 3. , 3.4, 3.4, 2.9, 3.1, 3. , 3.4, 3. ,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3.4, 3. , 3. , 3.3, 3.4, 3. ,
       3. , 3. , 3.4, 3.2, 3.1, 3.4, 3. , 3. , 3.1, 3.2, 3. , 3.1, 3. ,
       3.4, 3. , 2.3, 3.2, 3. , 3. , 3. , 3. , 3.2, 3. , 3.3, 3.2, 3.2,
       3. , 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 2. , 3. , 2.2, 2.9, 2.9,
       3.1, 3. , 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, 3. , 2.9, 3. , 2.8, 3. ,
       2.9, 2.6, 2.4, 2.4, 2.7, 2.7, 3. , 3.4, 3.1, 2.3, 3. , 2.5, 2.6,
       3. , 3. , 2.3, 2.7, 3. , 2.9, 2.9, 2.5, 2.8, 3.3, 2.7, 3. , 2.9,
       3. , 3. , 2.5, 2.9, 2.5, 3. , 3.2, 2.7, 3. , 2.5, 2.8, 3.2, 3. ,
       3. , 2.6, 2.2, 3.2, 2.8, 2.8, 2.7, 3.3, 3.2, 2.8, 3. , 2.8, 3. ,
       2.8, 3. , 2.8, 2.8, 2.6, 3. , 3.4, 3. , 3. , 3.1, 3.1, 3.1, 2.7,
       3.2, 3.3, 3. , 2.5, 3. , 3.4, 3. , 2.8, 2.8, 2.7, 3.3, 3.2, 2.5,
       2.9, 2.5, 3. , 2.8, 2.8, 2.7, 3. , 3.2, 2.7], dtype=float32)

In [64]:
a['arr_2'] #petal_length

array([1.4     , 1.4     , 1.3     , 1.5     , 1.4     , 1.7     ,
       1.4     , 1.5     , 1.4     , 4.022641, 1.5     , 1.6     ,
       1.4     , 1.1     , 1.2     , 1.5     , 1.3     , 1.4     ,
       1.7     , 1.5     , 1.7     , 1.5     , 1.      , 1.7     ,
       1.9     , 1.6     , 1.6     , 1.5     , 1.4     , 1.6     ,
       1.6     , 1.5     , 1.5     , 1.4     , 1.5     , 1.2     ,
       1.3     , 1.5     , 1.3     , 1.5     , 1.3     , 4.022641,
       1.3     , 1.6     , 1.9     , 1.4     , 1.6     , 1.4     ,
       1.5     , 1.4     , 4.7     , 4.5     , 4.9     , 4.      ,
       4.6     , 4.5     , 4.7     , 3.3     , 4.6     , 3.9     ,
       3.5     , 4.2     , 4.      , 4.7     , 3.6     , 4.4     ,
       4.5     , 4.1     , 4.5     , 3.9     , 4.8     , 4.      ,
       4.9     , 4.7     , 4.3     , 4.4     , 4.8     , 5.      ,
       4.5     , 3.5     , 4.022641, 3.7     , 3.9     , 4.022641,
       4.5     , 4.5     , 4.7     , 4.4     , 4.1     , 4.   

In [65]:
a['arr_3'] #petal_width

array([0.2, 0.2, 0.2, 1.5, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 1.5,
       0.1, 0.2, 0.4, 0.4, 0.3, 0.3, 0.3, 0.2, 0.4, 0.2, 0.5, 0.2, 0.2,
       0.4, 0.2, 1.5, 0.2, 0.2, 0.4, 0.1, 0.2, 0.1, 0.2, 0.2, 0.1, 0.2,
       0.2, 0.3, 0.3, 0.2, 0.6, 0.4, 0.3, 0.2, 0.2, 0.2, 0.2, 1.4, 1.5,
       1.5, 1.3, 1.5, 1.3, 1.6, 1.5, 1.3, 1.4, 1. , 1.5, 1. , 1.4, 1.3,
       1.4, 1.5, 1. , 1.5, 1.1, 1.8, 1.3, 1.5, 1.2, 1.3, 1.4, 1.4, 1.7,
       1.5, 1. , 1.1, 1. , 1.2, 1.6, 1.5, 1.6, 1.5, 1.3, 1.3, 1.3, 1.2,
       1.4, 1.2, 1. , 1.3, 1.2, 1.3, 1.3, 1.5, 1.3, 1.5, 1.9, 1.5, 1.8,
       1.5, 1.5, 1.7, 1.8, 1.8, 1.5, 2. , 1.9, 1.5, 2. , 1.5, 1.5, 1.8,
       1.5, 1.5, 1.5, 1.5, 2. , 2. , 1.8, 1.5, 1.8, 1.8, 1.8, 1.5, 1.6,
       1.9, 2. , 1.5, 1.5, 1.4, 1.5, 1.5, 1.8, 1.8, 1.5, 1.5, 1.5, 1.9,
       1.5, 1.5, 1.5, 1.9, 2. , 1.5, 1.8, 2. , 2. , 1.8, 1.5, 1.8, 1.7,
       1.8, 1.8, 1.8, 2. , 2. , 1.8, 1.5, 2. , 1.9], dtype=float32)