### Write a python code to create a array in different ways

In [1]:
# from list
list1 = [1,2,3,4,5,6,7,8]

In [2]:
import numpy as np

In [3]:
arr = np.array(list1)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
type(arr)

numpy.ndarray

In [6]:
# from tuple
tup = (1,2,3,49,6,7,8,25)

In [7]:
arr1 = np.array(tup)
arr1

array([ 1,  2,  3, 49,  6,  7,  8, 25])

In [8]:
type(arr1)

numpy.ndarray

In [9]:
# direct array creation
arr2 = np.array([1,2,3,4,5,6,44,50,69])
arr2

array([ 1,  2,  3,  4,  5,  6, 44, 50, 69])

### Array Creation

* Create a 1D Numpy array containing the first 12 positive integers as arr1.

* Create a 1D Numpy array1 with 20 elements containing integers between 0 and 12 using linspace.

In [10]:
# a
arr1 = np.arange(1,13)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [11]:
# b 
array1 = np.linspace(0,12,20)
array1

array([ 0.        ,  0.63157895,  1.26315789,  1.89473684,  2.52631579,
        3.15789474,  3.78947368,  4.42105263,  5.05263158,  5.68421053,
        6.31578947,  6.94736842,  7.57894737,  8.21052632,  8.84210526,
        9.47368421, 10.10526316, 10.73684211, 11.36842105, 12.        ])

### Find all atrributes of array1 and array2

In [12]:
array1 = np.arange(1,13)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [13]:
array2 =  np.linspace(0,12,20)
array2

array([ 0.        ,  0.63157895,  1.26315789,  1.89473684,  2.52631579,
        3.15789474,  3.78947368,  4.42105263,  5.05263158,  5.68421053,
        6.31578947,  6.94736842,  7.57894737,  8.21052632,  8.84210526,
        9.47368421, 10.10526316, 10.73684211, 11.36842105, 12.        ])

### Attributes of Array1

In [15]:
array1.ndim

1

In [16]:
array1.dtype

dtype('int32')

In [17]:
array1.size

12

In [18]:
array1.nbytes

48

In [19]:
array1.itemsize

4

### Attributes of array2

In [20]:
array2.ndim

1

In [21]:
array2.size

20

In [22]:
array2.nbytes

160

In [23]:
array2.dtype

dtype('float64')

In [24]:
array2.itemsize

8

### Measure of central tendancy of array1

In [25]:
# Mean
np.mean(array1)

6.5

In [26]:
#median
np.median(array1)

6.5

### Measure of spread of array1

In [27]:
# range 
range1 = np.max(array1)-np.min(array1)
range1

11

In [28]:
# varince
np.var(array1)

11.916666666666666

In [29]:
# std
np.std(array1)

3.452052529534663

#### IOR of array1

In [30]:
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [31]:
q3 = np.percentile(array1,75)
q3

9.25

In [32]:
q1 = np.percentile(array1,25)
q1

3.75

In [33]:
IQR = q3-q1
IQR

5.5

### To find outlier

In [34]:
lower_limit = q1-(1.5 * IQR)
lower_limit

-4.5

In [35]:
upper_limit = q3+(1.5*IQR)
upper_limit

17.5

In [36]:
array1>upper_limit

array([False, False, False, False, False, False, False, False, False,
       False, False, False])

In [37]:
array1<lower_limit

array([False, False, False, False, False, False, False, False, False,
       False, False, False])

* From above upper limit and lower limit both case are fail, hence there is no outlier

### Measure of central Tendancy of array2

In [38]:
array2

array([ 0.        ,  0.63157895,  1.26315789,  1.89473684,  2.52631579,
        3.15789474,  3.78947368,  4.42105263,  5.05263158,  5.68421053,
        6.31578947,  6.94736842,  7.57894737,  8.21052632,  8.84210526,
        9.47368421, 10.10526316, 10.73684211, 11.36842105, 12.        ])

In [39]:
# mean
np.mean(array2)

5.999999999999999

In [40]:
# median
np.median(array2)

6.0

### Measure of spread

In [41]:
# range
range2 = np.max(array2)-np.min(array2)
range2

12.0

In [42]:
# varinace
np.var(array2)

13.26315789473684

In [43]:
# std
np.std(array2)

3.6418618720013036

#### IQR

In [44]:
q1 = np.percentile(array2,25)
q1

3.0

In [45]:
q3 = np.percentile(array2,75)
q3

9.0

In [46]:
# IQR
IQR = q3-q1
IQR

6.0

### To find outlier of array2

In [47]:
array2

array([ 0.        ,  0.63157895,  1.26315789,  1.89473684,  2.52631579,
        3.15789474,  3.78947368,  4.42105263,  5.05263158,  5.68421053,
        6.31578947,  6.94736842,  7.57894737,  8.21052632,  8.84210526,
        9.47368421, 10.10526316, 10.73684211, 11.36842105, 12.        ])

In [48]:
lower_limit = q1-(1.5*IQR)
lower_limit

-6.0

In [49]:
upper_limit = q3+(1.5*IQR)
upper_limit

18.0

In [50]:
array2>upper_limit

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [51]:
array2<lower_limit

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

* from above upper limit and lower limit both case are fail, hence there is no outlier